# Generated by Django 4.2.4 on 2023-08-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ixaya', '0002_patrocinador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntryBlog',
            new_name='Blogpost',
        ),
    ]
