# Generated by Django 4.2.4 on 2023-08-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixaya', '0004_rename_images_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='resume',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
