# Generated by Django 4.2.4 on 2023-08-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixaya', '0005_blogpost_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
