# Generated by Django 4.2.4 on 2023-08-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixaya', '0006_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
