# Generated by Django 4.2.4 on 2023-08-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixaya', '0007_blogpost_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
