# Generated by Django 4.2.4 on 2023-08-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixaya', '0009_blogpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinador',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sponsors/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
